### PR TITLE
Fix security of ryzenadj feature

### PR DESCRIPTION
**Pull request by VisualEhrmanntraut**
Replaces script exposing user password with system LaunchDaemon and fetches ryzenadj from this repository instead.
Note: Untested, as I cannot build this on my M3 MacBook Pro and my testing AMD laptop is too slow. I tested the commands however, and it should work.

### CODE REVIEW

**Comment by royalgraphx** [comment]
Visual, you need to teach your little prodigies better, HAHAHA shitty ass code manz can't even hide user input, I can't believe i made you waste time working on a PR for this, have a great day :3

**Comment by VisualEhrmanntraut** [comment]
We were discussing privately about the creation of this Pull Request before you even submitted yours or replied to the message in AMD OSX. It just took me longer to create because I put more effort than your bandaid solution.

Screenshot 2024-09-26 at 23 03 31
Screenshot 2024-09-26 at 23 04 26

Nobody gives a shit about you.

I have archived this page with your incredibly terrible comment here: https://web.archive.org/web/20240926195931/https://github.com/alvindimas05/AMDHelper/pull/5 in case you decide to delete it and pretend I'm delusional.

**Comment by royalgraphx** [comment]
Why are you always so paranoid people will delete their comments about you? lmfao no one ever thinks about that nor are they scared to remove comments made, as they are clearly made with intention. I fully intend to keep the comment up, it does nothing for me or against me LMAO

it shows exactly where your priorities are at, you claim to want to assist your team members yet you never do. Only when it becomes convenient for you, do you ever actually help them :P again, absolutely funny I made you waste time on a PR! Instead of me sending a message in AMD OS X where you loveeee spying, explaining what he did wrong in the ONE LINE, I instead made it a PR, so Alvin couldn't take what I was going to teach him about making the text be masked using the library he chose, and commit it on his own since I knew he wouldn't give me credit LOL, certified funny moment. Have a good day!

**Comment by VisualEhrmanntraut** [comment]
I don't even need to say anything, your comment gives monumental delulu energy.

**Pull request merged**
